# Generated by Django 5.1.2 on 2024-10-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='title',
            field=models.CharField(default='enter title', max_length=50),
        ),
    ]
